### ISSUE TITLE
Invitación para participar en Hackathon Nicaragua 2017

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#1]
Por medio de la presente, les extendemos la invitación para formar parte del Festival Tecnológico más grande del país, Hackathon Nicaragua 2017.
 
En el Hackathon Nicaragua se desarrollará una feria con duración de 2 días continuos, 25 y 26 de noviembre, en el Centro de Convenciones Olof Palme.
 
Contaremos con la participación de Empresas y Comunidades Tecnológicas que estarán disponibles para el público en general, de forma totalmente gratuita.
 
El motivo de esta carta es para invitar a su Comunidad Javascript Nicaragua a apoyar el Festival Tecnológico Hackathon Nicaragua 2017, a través de las siguientes líneas de apoyo: 
 
-   **Stand**: espacio dentro de la feria tecnológica, donde la comunidad expone y presenta sus actividades.
 
-   **Mentores**: asistencia técnica donde brindarán apoyo a los equipos participantes de la competencia.
 
-   **Charlas/Conferencias**: apoyo por medio de expositores capacitados para brindar charlas y conferencias en temas relacionados a sus actividades.
 
Importante: Las propuestas de ponentes con sus temáticas incluídas deben de ser enviadas hasta el 5 de noviembre, y luego, pasarán un proceso de pre selección en un plazo de una semana, donde serán confirmados los seleccionados para participar como ponentes en el Hackathon Nicaragua 2017. 
 
Atentos a sus respuestas.
Equipo Organizativo Hackathon Nicaragua 2017.

https://www.facebook.com/events/1738624739533422/

----------

Organización
==========

**Stand**

- @LaurenceM10 (25 nov)

**Mentores**

- @paulomcnally (25/26 nov)
- @jarbitlira (25/26 nov)

**Charlas/Conferencias**

- @juanpicado - Verdaccio como registro privado de npm

## Necesidades:

1 Camiseta para @LaurenceM10.
1 Camiseta para @paulomcnally.
1 Camiseta para @jarbitlira.
1 Almuerzo para @LaurenceM10.

**Comment by juanpicado** [comment]
Mi nickname es @juanpicado @paulomcnally

**Comment by paulomcnally** [comment]
Actualizado @juanpicado.

**Comment by paulomcnally** [comment]
Nos rechazaron una charla sobre js.org https://github.com/js-org/js.org/issues/19#issuecomment-339912771 :/
