### ISSUE TITLE
Propuesta de Apoyo en Whatsapp

### ISSUE THREAD

**Issue by billiramirez** [js-ni/events#104]
Ante la eventualidad de estar solamente dos organizadores, hemos hecho la propuesta de solicitar el apoyo de Alfonso Gomez @victorstein y conceder permisos de `admin` para que pueda ayudarnos a moderar la actividad en ese canal.

Esta propuesta se basa en el apoyo constante ha tenido con la comunidad y mayormente por medio de Whatsapp.

Quedariamos en espera de su respuesta.

**Comment by jonariv09** [comment]
Apoyo la de idea de hacer admin a Alfonso, muy activo y con bastante disposicion de ayudar ya que con ese fin fue que cree ese grupo y ahora es de la comunidad.

**Comment by victorstein** [comment]
Gracias por tomarme en cuenta para ayudar a administrar el grupo de WhatsApp. Va a ser un gusto ayudarles el tiempo que pueda!

**Comment by billiramirez** [comment]
Muchas gracias @victorstein procederemos a brindarte los permisos correspondiente para Slack.

**Comment by castillo05** [comment]
Excelente propuesta...!

**Comment by paulomcnally** [comment]
![Captura de Pantalla 2020-05-25 a la(s) 21 09 49](https://user-images.githubusercontent.com/181533/82856741-191bf100-9ecc-11ea-9537-240c7081c1f1.png)

Listo @victorstein
