### ISSUE TITLE
Propuesta de Apoyo en Slack

### ISSUE THREAD

**Issue by billiramirez** [js-ni/events#105]
Ante la eventualidad de estar solamente dos organizadores, hemos hecho la propuesta de solicitar el apoyo de Luis Guido @luchonetvv y conceder permisos de `admin` para que pueda ayudarnos a moderar la actividad en ese canal.

Esta propuesta se basa en el apoyo constante ha tenido con la comunidad y mayormente por medio de Slack. 

Quedaríamos en espera de su respuesta.

**Comment by luchonetvv** [comment]
Vaya, interesante propuesta claro que sí @billiramirez trataré de colaborar ha como he venido haciéndolo y más de ser posible, con gusto.

**Comment by billiramirez** [comment]
Muchas gracias @luchonetvv procederemos a brindarte los permisos correspondiente para Whatsapp.

**Comment by paulomcnally** [comment]
![Captura de Pantalla 2020-05-25 a la(s) 21 07 41](https://user-images.githubusercontent.com/181533/82856659-cfcba180-9ecb-11ea-878b-0ed1184bf789.png)

Listo @luchonetvv
