### ISSUE TITLE
Solicitar los permisos de las redes sociales y otros canales de comunicación a Jose.

### ISSUE THREAD

**Issue by billiramirez** [js-ni/events#107]
Dado que @jonariv09 no podrá seguirnos acompañando como organizador de la comunidad, le solicitamos nos de los accesos primarios en las redes sociales.

- [x] En Slack: `Primary Owner`
- [x] En Whatsapp: Se necesita que abandone el grupo y vuelva a entrar ya que whatsapp no permite quitarle el permiso de `admin` ya que el creó el grupo.
- [x] Instagram
- [x] Gmail
- [x] Twitter

![image](https://user-images.githubusercontent.com/22375999/82856070-53848e80-9eca-11ea-9d0d-73619d36a15e.png)

![image](https://user-images.githubusercontent.com/22375999/82856101-5b443300-9eca-11ea-903d-cf77b0326027.png)

**Comment by jonariv09** [comment]
El instagram y el gmail tambien!

**Comment by paulomcnally** [comment]
@billiramirez Listo **Slack** y listo **Instagram**

**Comment by jonariv09** [comment]
@paulomcnally twitter ya no lo tenes?
