### ISSUE TITLE
Javascript en la Semana - 2020 - 40

### ISSUE THREAD

**Issue by billiramirez** [js-ni/events#116]
- https://es.digitaltrends.com/computadoras/microsoft-curso-javascript/ (https://github.com/microsoft/beginners-intro-javascript-node)

- https://www.30secondsofcode.org/js/p/1

- https://github.com/FreeTubeApp/FreeTube

- [Strapi Headless CMS]( https://strapi.io/)
- [Toast](https://www.toast.dev/)

**Comment by carloslenondavis** [comment]
- @Reactjs v17.0.0
- Introducing the New JSX Transform
- React 2020 Community Survey
- Front End Frameworks
- Redux is definitely NOT dead 
- @headlessui/vue@v0.2.0
