### ISSUE TITLE
Js en la Semana - 2020 - 41

### ISSUE THREAD

**Issue by billiramirez** [js-ni/events#117]

**Comment by paulomcnally** [comment]
https://jsconf.mx/ Se viene la JS Conf MX

**Comment by paulomcnally** [comment]
https://strongloop.com/strongblog/2020-lb3-eol/ Es momento de dejar de usar Loopback 3

**Comment by paulomcnally** [comment]
https://github.com/elsaland/elsa Elsa un runtime JavaScript escrito en Go

**Comment by billiramirez** [comment]
- [React Submit](https://reactsummit.com/)

**Comment by billiramirez** [comment]
- [npkill](https://www.npmjs.com/package/npkill)

**Comment by billiramirez** [comment]
[Gatsby Desktop](https://github.com/gatsbyjs/desktop)
