### ISSUE TITLE
Elaborar formato de live

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#13]
Propuesta Mc
1. Una persona que este con las cámaras
2. Presentadora
3. Expositor

**Comment by paulomcnally** [comment]
@clenondavis seria genial si creas un archivo .md en este repositorio con el formato de para los JSTaks - Taller y los JSTalks - Entrevistas/podcasts.

**Comment by paulomcnally** [comment]
@clenondavis esto no se hizo, crees vale la pena hacerlo para una futura? De hecho luego de la mala experiencia que tuvimos con la más reciente no se si aplica esto.

**Comment by paulomcnally** [comment]
no se obtuvo respuesta, al final se ha estado creando formatos para los lives y se ha documentado en otros issues.

**Comment by carloslenondavis** [comment]
SI, no agregue propusta, porque ya no aplica. Hemos mejorado y alineado en ese aspecto
