### ISSUE TITLE
Publicar post de evento live

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#15]
- [x] Definir el contenido de la descripción
- [x] Crear el evento
- [x] Publicar en Instagram (José)
- [x] Publicar en Whatsapp (José)
- [ ] Publicar en G+ (José)
- [ ] Publicar en slack (Lenon)
- [x] Publicar en facebook (Lenon)

**Comment by carloslenondavis** [comment]
Publico Martes en facebook y Slack a las 08:00AM

**Comment by paulomcnally** [comment]
Enlace -> https://www.facebook.com/JavaScriptNicaragua/photos/a.164907387450155/555247005082856/?type=3&theater
