### ISSUE TITLE
Definir bases para live 31 Marzo

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#17]
- [x] Definir Tema
- [x] Definir Ponente
EL target para este Live no será enfocado en técnico.

**Comment by billiramirez** [comment]
Recibí el feedback de una persona y me dijo que quizá no repitamos charlas, por ejemplo el taller que hubo hace 2 semanas de graphql, quizá este live sea no técnico.

**Comment by paulomcnally** [comment]
@billiramirez según lo que hablamos, no podemos basarnos en otras comunidades, no podemos dejar nuestra comunidad sin charlas/talleres por el hecho de que otra comunidad ya ha impartido temas (ejemplo GraphQL).

**Comment by hosmelq** [comment]
Estoy de acuerdo con @paulomcnally, no debería de ser un inconveniente que otra comunidad haya dado un taller sobre el mismo tema.

Tampoco se va a hablar exactamente de los mismo y va a atender la misma gente.

Yo atendí a ese taller y quedaron muchas cosas en el aire y otras mal explicadas.

**Comment by carloslenondavis** [comment]
Temas:

- [x] 1. Como conseguir trabajo fuera de Nicaragua?
- [ ] 2. Cuando decir no a una oferta
- [x] 3. Cuanto y porque tan caro (Salario)
- [ ] 4. Debo de aprender algo mas?

Formato
- Preguntas y respuestas

Dinámica:
- Respuestas cronometrada

**Comment by carloslenondavis** [comment]
Votación del tema

**Comment by paulomcnally** [comment]
Voto por 1 y 3

**Comment by billiramirez** [comment]
1 y 3.

**Comment by carloslenondavis** [comment]
Voto por 1 y 3

**Comment by jonariv09** [comment]
1 y 3

**Comment by carloslenondavis** [comment]
*Formato*
- Moderador
- Cantidad de participantes
 

- [x]  @paulomcnally propone moderador + 4

**Comment by carloslenondavis** [comment]
Propuestas de Ponentes?

**Comment by carloslenondavis** [comment]
@paulomcnally proponen por zoom,

**Comment by carloslenondavis** [comment]
Al lunes 02 de marzo, entregar los expositores propuestos

**Comment by carloslenondavis** [comment]
TODO
- [ ] Arte para miniatura de youtube (Mc) #32 
- [ ] Edición Vídeo (Alfonso y Gustavo)  #33 
- [ ] Formato de evento en vivo (Todos) #34 
- [x] Pasar estos todo a github kanban (Billi)  #38 
- [x] Conseguir expositores (Mc, Lenon, Billi, Jose) #35 
- [ ] Post de las redes sociales (Facebook, slack) #36 
- [ ] Configurar el live para youtube (Mc) #37

**Comment by paulomcnally** [comment]
@cabolanoz nos acompañará en este evento.

**Comment by paulomcnally** [comment]
Esto quedó listo. Bien hecho Team.
