### ISSUE TITLE
Crear políticas para las redes sociales.

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#19]

**Comment by jonariv09** [comment]
Las reglas tengo para el grupo de WhatsApp:

1. No OFF-TOPIC, es decir dar publicidad a otras tecnologias, o desarrollar temas basados en otras tecnologias que no sean de JavaScript. ❕❗
2. Respetar las opiniones que tengan los demas miembros del grupo. 👏🏽
3. Se podra compartir contenidos o rescursos que sean de programacion y de JavaScript o tecnologias realacionadas, solamente.
4. EL QUE PONGA SPAM, SERÁ BANEADO. ❌
5. Por ningun motivo se tolerara intimidación, acoso, abuso, discriminación, comunicación despectiva o degradante. 
6. No contenido pornografico en stickers, memes, imagenes, audios, links, u otros. ⚠
7. Se permite publicar ofertas de trabajo relacionadas con JavaScript. 🛄

**Comment by jonariv09** [comment]
Github, se necesitan mejorar, ya puse algunos issues ahi, y esas mismas son las de la pagina de facebook.

**Comment by jonariv09** [comment]
Creo que son los dos medios que mas necesitan control con esto de reglas.
