### ISSUE TITLE
Intereses

### ISSUE THREAD

**Issue by juanpicado** [js-ni/events#2]
Ya que la organizacion agrupa muchisima gente, seria genial saber que intereses, habilidades tiene cada quien, se podria crear un markdown y una tabla con los avatares de cada uno, las columnas podrian tener cosas como habilidades, intereses, etc etc ... quizas de ahi salen mas ideas o formas de colaboracion.  Por ejemplo,  pueda ser que alguien este interesado en aprender Vue.js pero no conozca a nadie mas que lo use o gente que quiera contribuir a open source y nos sabe como empezar.

Tambien crear un canal de **slack** seria una forma de comunicacion interesante.

**Comment by paulomcnally** [comment]
@oscarmcm podrías subir algo a heroku para subscripción al Slack de la comunidad?

@juanpicado y si se hace un repo con issues de profiles?

**Comment by juanpicado** [comment]
@paulomcnally cualquier cosa que permita saber quien es quien valdria.

**Comment by oscarmcm** [comment]
@juanpicado hemos creado un repositorio con alguna información util https://github.com/js-ni/people probablemente tengamos que agregar un CONTRIBUTING.md para los nuevos.

@paulomcnally pasame los keys para subirlo a heroku

**Comment by juanpicado** [comment]
Cool, eso fue rapido

**Comment by paulomcnally** [comment]
@oscarmcm no usamos heroku. Usamos github pages. Si te vas al repo del sitio veras los comandos.

https://github.com/js-ni/ni
