### ISSUE TITLE
Crear encuesta para elegir nombre de la comunidad

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#22]

**Comment by jonariv09** [comment]
La proxima reunion les paso esto

**Comment by jonariv09** [comment]
Decidi hacer las encuestas en una sola no se que les parece.

Esta en la carpeta de google drive en la subcarpeta Encuestas

**Comment by jonariv09** [comment]
Bueno este es el link para acceder a la encuesta hay dos secciones una para elegir el nombre de la comunidad y el otra las fechas de los meets

https://forms.gle/gtZPGduinJSdjGLK6

**Comment by carloslenondavis** [comment]
@jonariv09  Propuesta de @paulomcnally es crear una cuesta en facebook

**Comment by jonariv09** [comment]
Me parece, esta bien

No llenen esta encuesta todavia porque son borradores que se estan realizando para las encuestas
