### ISSUE TITLE
Busqueda Host

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#24]

**Comment by paulomcnally** [comment]
Se había mencionado Nica Source.

**Comment by billiramirez** [comment]
También se mencionó la persona que podia proveer espacio en Nindiri.

**Comment by carloslenondavis** [comment]
Mañana hablare con Nicasource

**Comment by paulomcnally** [comment]
Esto no quedo en nada, aun que al final no pudimos proceder por COVID-19, @clenondavis en caso de que se logró contactar a alguien por favor pedir disculpas de nuestra parte (como comunidad).
