### ISSUE TITLE
Definir Fecha

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#26]

**Comment by paulomcnally** [comment]
Propongo sábado de la tercera semana de Abril.

**Comment by carloslenondavis** [comment]
`Propongo`
Dia: Domingo 
Horario: 09 - 01pm / 02 - 05pm

**Comment by billiramirez** [comment]
Propongo Sabado 25 de abril, por la mañana. 
8:30 am

**Comment by jonariv09** [comment]
Me gustaria Sábado 25 de abril, 2:00pm.

**Comment by jonariv09** [comment]
Decidi hacer las encuestas en una sola no se que les parece.

Esta en la carpeta de google drive en la subcarpeta Encuestas

**Comment by carloslenondavis** [comment]
Se quedó por decisión unánime el Sábado 25 de Abril

**Comment by paulomcnally** [comment]
Este evento presencial se canceló
