### ISSUE TITLE
Definir encuesta para día

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#29]

**Comment by jonariv09** [comment]
Decidi hacer las encuestas en una sola no se que les parece.

Esta en la carpeta de google drive en la subcarpeta Encuestas

**Comment by jonariv09** [comment]
Bueno este es el link para acceder a la encuesta hay dos secciones una para elegir el nombre de la comunidad y el otra las fechas de los meets

https://forms.gle/gtZPGduinJSdjGLK6

**Comment by paulomcnally** [comment]
@jonariv09 opino nos vayamos por Facebook Encuestas.

**Comment by jonariv09** [comment]
Me parece, esta bien

No llenen esta encuesta todavia porque son borradores que se estan realizando para las encuestas

**Comment by jonariv09** [comment]
Bueno, debido a la obvia situacion del pais, y que se tratara en la mayor medida posible de hacer las cosas de forma remota considero conveniente hacer mas adelante esta encuesta.
