### ISSUE TITLE
Conseguir expositores

### ISSUE THREAD

**Issue by billiramirez** [js-ni/events#35]

**Comment by billiramirez** [comment]
Hablé con mi compañero de trabajo y accedió a compartir su experiencia para el tema de "Cómo conseguí mi primer trabajo para una empresa fuera del pais".

**Comment by carloslenondavis** [comment]
Hola @billiramirez basados en nuestra reunión sería bueno nos compartas un link sobre el perfil de tu amigo

**Comment by carloslenondavis** [comment]
@paulomcnally podes por favor compartir por acá los datos de la persona que propones, asi quede guardado la info

**Comment by billiramirez** [comment]
@clenondavis este es su [LinkedIn](https://www.linkedin.com/in/eleazar-gait%C3%A1n-198b22137/) , tambien su [website](https://elotgamu.github.io/)

**Comment by paulomcnally** [comment]
https://www.linkedin.com/in/cesarbolanosandino/ @clenondavis
