### ISSUE TITLE
Pasar los TODO del evento de Marzo 31 a Kanban

### ISSUE THREAD

**Issue by billiramirez** [js-ni/events#38]
Pasar cada item del issue "Definir bases para live 31 de Marzo" a Kanban.

**Comment by paulomcnally** [comment]
No tiene descripción. @billiramirez a que se refiere esto?

**Comment by billiramirez** [comment]
Esto fue un issue que se referia a los items de "Definir bases para live 31 de Marzo" pasarlos a TODO.
