### ISSUE TITLE
Conseguir Arte Publicidad

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#4]
Requerimos el diseño para el evento.

Opcional una plantilla que reutilizaremos siempre.

**Comment by paulomcnally** [comment]
Nombre del taller: Graphql 101

Temas:
* Configuración con express
* Aprendiendo a escribir esquemas
* Mi primer resolver

Cargo: Director de desarrollo de software y aplicaciones en Top Floor Marketing
5+ años de experiencia

**Comment by paulomcnally** [comment]
![WhatsApp Image 2020-02-17 at 9 35 25 PM](https://user-images.githubusercontent.com/181533/74879159-328e2980-532e-11ea-9b7a-a0bd38514101.jpeg)

**Comment by paulomcnally** [comment]
@LissTrujillo nos apoyará con el diseño del arte para redes sociales.

**Comment by dianalih** [comment]
Hola les dejo unas propuestas,
![1](https://user-images.githubusercontent.com/24735404/74900865-aea46380-5366-11ea-9b4d-6a6e89a62b97.png)
![2](https://user-images.githubusercontent.com/24735404/74900897-c845ab00-5366-11ea-8e25-a8b7853eb339.png)
![3](https://user-images.githubusercontent.com/24735404/74900904-cd0a5f00-5366-11ea-8766-74cba3926bab.png)
![4](https://user-images.githubusercontent.com/24735404/74900908-d1cf1300-5366-11ea-900a-c3ff6d17cfdc.png)
![5](https://user-images.githubusercontent.com/24735404/74900922-de536b80-5366-11ea-9607-5fa6be71ba78.png)




 es algo como un flyer si debería ser diferente solo me dicen :)
