### ISSUE TITLE
Live #Graphql101 07 Marz

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#44]

**Comment by paulomcnally** [comment]
Mis comentarios:
- Cometimos el error de tener off el micrófono de la llamada de Zoom. [Ver configuración de Zoom](https://user-images.githubusercontent.com/181533/76275668-7a2b1580-6249-11ea-813f-56c7d2aed2a8.jpeg)
- La maquina donde se estaba ejecutando OBS se recalentó, eso hizo que hubieran varias partes del live donde se perdía tanto audio y video.

**Conclusiones**:
- No tenemos equipo adecuado para hacer streaming de pantalla. Debemos hacer varias pruebas de streaming de video con celulares para ver si logramos tener streaming funcionales.
