### ISSUE TITLE
Conseguir datos del expositor

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#5]
No estoy claros que datos serán pero ideal que tengamos un google form para enviarsela a los expositores.

**Comment by paulomcnally** [comment]
@jonariv09 ideal poner acá los datos del expositor.

**Comment by jonariv09** [comment]
- Director de desarrollo de software y aplicaciones en Top Floor Marketing
- 5+ años de experiencia
- Stack preferido: MERNG, (Mongo, Express, React, Node, GraphQl)
- Duracion: 1h - 1 y 1/2 h

**Comment by jonariv09** [comment]
Yo le pedi esos, creo que pueden estar bien para el arte.
