### ISSUE TITLE
Contactar a Juan Picado para proponerle que nos haga un video con sus comentarios y opiniones acerca de la unión de NPM a Github.

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#50]
Se propone que Juan Picado se grabe a el mismo con su celular y nos de sus comentarios y opiniones acerca de la unión/compra de NPM hacia Github.

**Formato del video**:
- Horizontal
- 720p (1280x720)
- Duración mínima 5min.

@juanpicado nos concedería el derecho de replicar el video en todas nuestras redes sociales y otros medios que creamos convenientes. También la edición del video para mejoras de audio o video y a su vez agregar logos o marcas de la comunidad JavaScript.

**Comment by paulomcnally** [comment]
Ping @juanpicado

**Comment by juanpicado** [comment]
Lo siento, pero no estoy interesado en esta idea. Solo estoy interesado de hablar de Open Source y relacionado via streaming.

**Comment by paulomcnally** [comment]
Gracias @juanpicado
