### ISSUE TITLE
Hablar acerca de las normas en el grupo de Whatsapp / Slack

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#51]
Tenemos que ver si se están cumpliendo las normas en el grupo de Whatsapp.

**Comment by paulomcnally** [comment]
Desde ayer estoy en el grupo de Whatsapp, hoy me topé con el típico meme que no tiene nada que ver con `JavaScript`.

Les dejo contexto:

**1 - Se publica un `chiste`.**
![IMG_0962](https://user-images.githubusercontent.com/181533/77203818-0396df00-6ab7-11ea-8824-570e6163fd11.PNG)

**2 - Se intenta bromear acerca de el chiste cuando se le pregunta, acerca de la relación del `chiste` con `JavaScript`.**
![IMG_0961](https://user-images.githubusercontent.com/181533/77203937-4c4e9800-6ab7-11ea-9b88-a13e14b00292.PNG)

**3 - Se banea al usuario.**

Opino necesitamos identificar si el grupo de WhatsApp genera valor a la comunidad o si es algo que no tiene control.

Opino debemos entrar y moderar dicho grupo, por mi parte lo haré, no se ustedes @billiramirez @clenondavis

**Comment by jonariv09** [comment]
Seria bueno que se considere, aveces hacen bastantes publicaciones de ese tipo y ya he eliminado a varios.

**Comment by billiramirez** [comment]
Un procedimiento a seguir es banear y seguido de eso, volver a enviar las normas. Asi los demás sabrán el contexto y el porque se está eliminando, sirve como refresh.

**Comment by billiramirez** [comment]
El otro detalle @paulomcnally el dia que entré al grupo, solo estuve por 5 minutos y la cantidad de mensajes que entraban era bastante, lo cual hace imposible de trackear. Quizá entre todos se pueda a medida que se vayan idenficando.

**Comment by paulomcnally** [comment]
@billiramirez ese mismo día que entré lo noté, pero era un debate/discusión acerca de buenas prácticas o algo así, entonces eso si está bien.

**Comment by paulomcnally** [comment]
@jonariv09 podes compartir acá el link de la normas porfa?

**Comment by paulomcnally** [comment]
> Seria bueno que se considere, aveces hacen bastantes publicaciones de ese tipo y ya he eliminado a varios.

Has eliminado los comentarios o a los usuarios?

**Comment by jonariv09** [comment]
@paulomcnally he eliminado a los usuarios, porque han puesto cosas que van en contra de las normas que habiamos acordado nosotros que se pondrian

**Comment by jonariv09** [comment]
1. No OFF-TOPIC, es decir dar publicidad a otras tecnologias, o desarrollar temas basados en otras tecnologias que no sean de JavaScript. ❕❗
2. Respetar las opiniones que tengan los demas miembros del grupo. 👏🏽
3. Se podra compartir contenidos o rescursos que sean de programacion y de JavaScript o tecnologias realacionadas, solamente.
4. EL QUE PONGA SPAM, SERÁ BANEADO. ❌
5. Por ningun motivo se tolerara intimidación, acoso, abuso, discriminación, comunicación despectiva o degradante. 
6. No contenido pornografico en stickers, memes, imagenes, audios, links, u otros. ⚠
7. Se permite publicar ofertas de trabajo relacionadas con JavaScript. 🛄

**Comment by jonariv09** [comment]
Esas son las reglas en el grupo!

**Comment by dave-flr** [comment]
Han considerado usar otra app de mensajería como Telegram o Discord, ahi se pueden configurar bot para que silencien a cierto usuario o que banee a otro dependiendo de que tipo de contenido se mandó, tambien existe el modo lento para evitar flood, entre un sin fin de mejores funcionalidades

**Comment by victorstein** [comment]
Buenas noches,

**TL;DR**
Necesitamos mas moderadores.

**Para los que les gusta leer:**

Espero no ser inoportuno con mis comentarios, pero vi el issue abierto y me pareció interesante el tema que discuten.

El grupo de WhatsApp ha ido evolucionando bastante desde los días en que solo lo manejaba @jonariv09 y la comunidad es relativamente activa a cómo pudieron ver estos últimos días. El día del live @paulomcnally me comentaba sobre las ambiciones del grupo de JavaScript Nicaragua y como planea hacerlo algo más grande con conferencias de participantes internacionales.

Me parece excelente que tengan esas metas, pero para alcanzarlas se necesita una comunidad. Lamentablemente, ninguno de los otros canales (slack, discord, hangouts, facebook, youtube) son tan concurridos o utilizados como el de WhatsApp.

Esto podría deberse a muchas razones, me imagino que tiene que ver más con la cultura Nica y la falta de conocimientos de otras herramientas; sin embargo, el grupo necesita moderación permanente para lo cual @jonariv09 no da abasto. Ciertamente WhatsApp es la peor forma de moderar a una comunidad por su canal único para moderar temas.
Mientras no tengamos una comunidad activa por otros medios sugiero darle un poco más de importancia al grupo de WhatsApp porque podrían ser los cimientos de algo mucho más grande.

No estoy en contra de los BANS de los off-topic pero con la cantidad suficiente de moderadores se puede encaminar al grupo y mantenerlo activo para difundir información relevante y que los participantes no tengan miedo al BAN. No se ustedes, pero de dictadura ya tenemos mucho aquí en Nicaragua (xD) y permitir que los participantes piensen por si mismos y posteen bajo las normas del grupo va a ser vital para hacerlo crecer.

Supongo que mis sugerencias finales serian:

1. Necesitamos más moderadores
2. Necesitamos mas presencia de los admins. Que los conozca la comunidad. (no solo entrar y mutear el grupo).
3. Postear las reglas del grupo al menos una vez a la semana, hasta el punto en que la comunidad lo haga broma y puedan vivir con las reglas sin romperlas.
4. Promover el uso de otras herramientas mas adecuadas para moderar al grupo y empezar a mover el contenido a esas plataformas para educar a la comunidad
5. Empezar a compartir arte, videos, cosas hechas por la comunidad en los canales oficiales para generar entusiasmo y expectativa.

Si puedo serles de ayuda en algo pueden hacérmelo saber.

**Comment by carloslenondavis** [comment]
Que tal chicos,

lo siento por no estar al tanto de estos comments,
Personalmente yo siempre estoy al tanto de los grupos, solo que a veces no comento para efecto de no generar cuellos de botellas o bien quizas no hay razon por el cual comentar

**Comment by carloslenondavis** [comment]
En estos días les daré mis observaciones sobre el tema
Saludes

**Comment by paulomcnally** [comment]
@clenondavis propone:

Usar Whatsapp para notificar (eventos, que hacer, como colaborar, etc) y usar otras herramientas (ejemplo Slack) para cuando pregunten cosas, o quieran compartir otras cosas.

@clenondavis editas cuando podas para que pongas tu idea completa.

**Comment by paulomcnally** [comment]
@jonariv09 opina hacer el esfuerzo por redireccionar a Slack. (Cuando escriban en WhatsApp).

**Comment by paulomcnally** [comment]
@clenondavis menciona una alternativa super interesante: Whatsapp Business para redireccionar a la gente.

**Comment by paulomcnally** [comment]
Aquí vamos a definir los canales/opciones/menu https://github.com/js-ni/events/issues/55

**Comment by SaulSomarriba** [comment]
Buenas noches @paulomcnally , me gustaria ser parte del grupo de whatsapp, aqui mi numero +505 87996201, gracias hermano, saludos.

**Comment by carloslenondavis** [comment]
Upps revise tarde, jaajajjaj

**Comment by carloslenondavis** [comment]
La idea es,

Paulatinamente ir despojando a `whatsapp` de tantas responsabilidades
- Chat
- Chistes
- Humor
- Información
- Consulta
- etc..

y poder solo usarlo para informativo y usarlo para dar publicidad a los diferentes canales de slack
