### ISSUE TITLE
Crear arte para live 31 marzo

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#54]
- Incluir avatar de los participantes

**Comment by jonariv09** [comment]
Tematicas:
1. Como conseguir trabajo fuera de Nicaragua?
2. Cuanto y porque tan caro (Salario)

**Comment by jonariv09** [comment]
Participantes:
- Cesar Bolaños
- Eleazar Gaitan
- Carlos Lenon
- Billi Ramirez

Host:
- Paulo McNally

Moderadora:
- Diana Huete

**Comment by paulomcnally** [comment]
@clenondavis Urgente, por favor compartir tu Avatar.

**Comment by paulomcnally** [comment]
@billiramirez  Urgente, por favor compartir tu Avatar.

**Comment by paulomcnally** [comment]
@cabolanoz Urgente, por favor compartir tu Avatar.

**Comment by paulomcnally** [comment]
@LissTrujillo Urgente, por favor compartir tu Avatar.

**Comment by paulomcnally** [comment]
@elotgamu Urgente, por favor compartir tu Avatar.

**Comment by elotgamu** [comment]
> @elotgamu Urgente, por favor compartir tu Avatar.

Pues, el mismo que uso en mi LinkedIn: https://drive.google.com/file/d/0B5bt-zBx9TpwRHlPVzllZDBfOXM/view?usp=sharing

Avísame si con ese está bien.

**Comment by dianalih** [comment]
Hola les dejo el arte siguiendo el mismo diseño del anterior que era lo que habían mencionado, faltan el avatar de @cabolanoz y de @clenondavis 
Me dicen que tal si hay algo que cambiarle o si probamos con otro diseño. 
![Experiencias](https://user-images.githubusercontent.com/24735404/77482975-b71c0e00-6dec-11ea-864b-b40dfe08c7fe.png)

**Comment by cabolanoz** [comment]
> @cabolanoz Urgente, por favor compartir tu Avatar.

@paulomcnally, te adjunto.

![IMG_20190622_161214](https://user-images.githubusercontent.com/469749/77579082-4eda3480-6e9f-11ea-9621-5795ccee041f.jpg)

**Comment by billiramirez** [comment]
Hola, @LissTrujillo  podrías modiificar mi nombre por fa? Gracias.

**Comment by dianalih** [comment]
Hola @billiramirez listo, recuerden que falta el avatar de @clenondavis
![Experiencias2](https://user-images.githubusercontent.com/24735404/77593081-2bbc7e80-6eb9-11ea-9233-42fe2eb8fd45.png)

**Comment by billiramirez** [comment]
Gracias @LissTrujillo

**Comment by paulomcnally** [comment]
@LissTrujillo podrías subir el PSD/AI?

Es qué hay cambios en el texto, ponerle signos de interrogación. De hecho podrías subir al repositorio esos archivos para versionarlos.

**Comment by paulomcnally** [comment]
@LissTrujillo me mencionó @clenondavis que podes usar el Avatar de GitHub.

**Comment by paulomcnally** [comment]
@LissTrujillo super importantes. -- Yo no soy parte de este evento --

Vos si, entonces hay que poner tu nombre y Avatar.

**Comment by paulomcnally** [comment]
**Moderador**:
- Diana Huete.

**Panelistas**
- Carlos Lenon
- Cesar Bolaños
- Billi Ramirez
- Eleazar Gaitán

**Comment by dianalih** [comment]
Les dejo ya con los cambios
![experiencias](https://user-images.githubusercontent.com/24735404/77800158-d2308d00-703b-11ea-85f3-651768d44a20.png)

**Comment by paulomcnally** [comment]
@LissTrujillo muchas gracias! Quedo muy bien.
