### ISSUE TITLE
Menu de alternativas para discusiones.

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#55]
Propuestas de canales/items que tendremos en Slack (u otras herramientas).

**Comment by paulomcnally** [comment]
- Librerías
- Proyectos
- Dudas
- [x]  Off Topic
- Memes

**Comment by billiramirez** [comment]
- Latest New
- Próximos Eventos
- [x] Feedback
- Politicas y Código de Conducta

**Comment by carloslenondavis** [comment]
- [x] Noticias
- [x] Eventos
- Proyectos Open Source
- Sponsor
- Exponente

**Comment by paulomcnally** [comment]
@jonariv09 solo vos faltas poner la lista de canales/menú.

**Comment by jonariv09** [comment]
- Oportunidades de trabajo
- Canales para cada `team` existente en la organización de git (`team-pagina-web`, `team-blog`, `team-design`, etc...)
- Encuestas

**Comment by jonariv09** [comment]
hay que eliminar varios canales también, yo los había creado en un inicio, pero creo que son rendundantes!

**Comment by paulomcnally** [comment]
@jonariv09 se encargará de percibir el feedback de los canales para slack y en el canal organizadores nos comentará, si en 24 horas no hay feedback él tomará la decision.
