### ISSUE TITLE
Crear un team para proyectos ideas opensource dirigidos por la comunidad

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#57]
Seria bueno subir propuesta de ideas

Se me viene a la mente `IronMan`
o bien un nombre que signifique idea, codigo libre, equipo, comunidad

**Comment by carloslenondavis** [comment]
Mientras agregare uno luego se vota y cambia

**Comment by jonariv09** [comment]
`SourceKeep Group`

**Comment by paulomcnally** [comment]
Opino debería haber un team por cada proyecto. No uno solo para varios proyectos.

**Comment by paulomcnally** [comment]
@clenondavis necesitamos salir de esto, lleva 21 días en `To do`, lo pasé a `In Progress` para que ya se proceda con esto.

**Comment by carloslenondavis** [comment]
@paulomcnally recorda que no hemos tenido meeting, por diferentes actividades. Creo que no es de prioridad alta, podemos dejarlo en todo e incluso cerrarlo.

**Comment by paulomcnally** [comment]
@clenondavis ya creó los teams.
