### ISSUE TITLE
Definir listados  de preguntas

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#58]
@jonariv09 sos el encargado de decidir las 10 preguntas.

5 de cada tema.

**Comment by billiramirez** [comment]
### Como conseguir trabajo fuera de Nicaragua  (propuestas)

- ¿Fue necesario tener una marca personal bien definida para conseguir un empleo del exterior? 
- En tu experiencia trabajando para empresas del exterior, ¿ En algún momento estuvo considerada la opción de obtener una visa de trabajo? En caso de ser así que te ofrecieron,  ¿Cuál fue tu reacción ante eso? 
- ¿ Qué es lo que usualmente sueles dar prioridad al decidir si trabajar o no para una empresa del exterior? ¿Salario, tecnología,  perks?  

### Cuanto y porque tan caro (Salario) => Propuesta

- ¿Cómo sueles negociar el salario propuesto? 
- ¿Que criterios utilizas para brindar tu propuesta  de salario? ¿ Costo de vida, Salud + Seguro, Perks, Renta?

**Comment by carloslenondavis** [comment]
# Conseguir trabajo fuera de `Nicaragua`?
- En donde puedo conseguir trabajo remoto con `expresas extranjeras`?
-  Cuales son las `tecnologías Javascript` que estan siendo `demandada`s en diferentes paises?
- Cual fue el proceso de `adaptacion` para trabajar para una empresa extranjera?
- Como sobrellevar las `discriminaciones` por ser nicaraguense?
- Has trabajado presencialmente `fuera` de Nicaragua? Cual fue la experiencia?
- Sera `confiable el pago` que te haran?
- Cuales son los aspectos a considerar para `elegir un puesto` con una empresa extrangera?
- Que pasa con el `seguro laboral`?
- Cuales son los `beneficios de trabajar remotamente` para una empresa extranjera?
- Cuando decir no?

# Cuanto y porque tan caro
- Cual debe ser mi `salario`?
- Como se cuando debo `ganar`?
- Aspectos para `negociar` un salario?
- Cuando debo decir no?
- Como debo negociar conmigo mismo ante la propuesta de un salario?
- Quien debe dar primero la oferta?
- Hasta donde podemos ser flexibles en la negociacion?

**Comment by paulomcnally** [comment]
## Conseguir trabajo fuera de Nicaragua?

- Cuánta experiencia debo tener para aplicar a un puesto en el extranjero.
- Del 1 al 10 cuanto debo saber de un lenguaje para aplicar a un puesto de ese lenguaje.
- Es necesario saber inglés para aplicar a puestos fuera de Nicaragua.
- Ademas de saber programar, que otros factores pueden ser importantes para ser un candidato interesante.

## Cuanto y porque tan caro?
- Debo mencionar mis expectativas altas en salarios de afuera o puede provocar que ni siquiera llegue a una entrevista.
- Cómo puedo saber cuanto debo ganar?
- Cuanto es el maximo que podría cobrar en un puesto Full Stack Senior?

**Comment by paulomcnally** [comment]
@jonariv09 por favor poner la lista de preguntas seleccionadas.

Ya mañana es el pre ensayo.

**Comment by jonariv09** [comment]
Perdon, solo la pase en slack se me olvido pasarla por aqui.

**Comment by jonariv09** [comment]
# ¿Cómo conseguir trabajo fuera de Nicaragua?

1. ¿ Qué es lo que usualmente sueles dar prioridad al decidir si trabajar o no para una empresa del exterior? ¿Salario, tecnología, perks?
2. Cuales son los beneficios de trabajar remotamente para una empresa extranjera?
3. ¿Del 1 al 10 cuanto debo saber de un lenguaje para aplicar a un puesto de ese lenguaje?
4. ¿Es necesario saber inglés para aplicar a puestos fuera de Nicaragua?
5. Cuánta experiencia debo tener para aplicar a un puesto en el extranjero.

# ¿Cuanto y porqué tan caro?

1. ¿Aspectos para negociar un salario? {

    Observación: No se si es el núcleo de la pregunta pero creo que se puede tratar un poco la 
    expertise, lo digo por motivos que cnsidero muy bueno tratar no solo el caso de FullStack Senior, 
    sino tambien un poco de Semi Senior y Junior.
}

2. ¿Hasta dónde podemos ser flexibles en la negociación?
3. ¿Cuanto es el máximo que podría cobrar en un puesto Full Stack Senior?
4. ¿Cómo sueles negociar el salario propuesto?
5. Cuando debo decir no?

**Comment by jonariv09** [comment]
Ahi estan considero que podrian ser del interes de muchos esas!

**Comment by clenondavis** [comment]
@jonariv09 que significa

> # ¿Cómo conseguir trabajo fuera de Nicaragua?
> 1. ¿ Qué es lo que usualmente sueles dar prioridad al decidir si trabajar o no para una empresa del exterior? ¿Salario, tecnología, perks?
> 2. Cuales son los beneficios de trabajar remotamente para una empresa extranjera?
> 3. ¿Del 1 al 10 cuanto debo saber de un lenguaje para aplicar a un puesto de ese lenguaje?
> 4. ¿Es necesario saber inglés para aplicar a puestos fuera de Nicaragua?
> 5. Cuánta experiencia debo tener para aplicar a un puesto en el extranjero.
> 
> # ¿Cuanto y porqué tan caro?
> 1. ¿Aspectos para negociar un salario? {
>    Observación: No se si es el núcleo de la pregunta pero creo que se puede tratar un poco la
>    expertise, lo digo por motivos que cnsidero muy bueno tratar no solo el caso de FullStack Senior,
>    sino tambien un poco de Semi Senior y Junior.
>    }
> 2. ¿Hasta dónde podemos ser flexibles en la negociación?
> 3. ¿Cuanto es el máximo que podría cobrar en un puesto Full Stack Senior?
> 4. ¿Cómo sueles negociar el salario propuesto?
> 5. Cuando debo decir no?

@jonariv09 que significa `perks`??

**Comment by jonariv09** [comment]
Son privilegios extras o beneficios que puede brindarte una empresa al trabajar en ella.

Segun decia el internet; si estoy mal porfa corríjanme.

**Comment by clenondavis** [comment]
Entendido, es primera vez que veo esa palabra

**Comment by jonariv09** [comment]
Igual yo.

**Comment by clenondavis** [comment]
Me la robe para futuro avatar ajajaaj
