### ISSUE TITLE
Comentarios borrados en WhatsApp

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#66]
En ocasiones accedo al grupo de WhatsApp y veo comentarios como este:

![436D4F98-5709-4E85-827A-E0D5C085F45D](https://user-images.githubusercontent.com/181533/77875355-14f58f00-720d-11ea-8282-d942432fadec.png)

No estoy claro si es motivo para ban o no pues por que no se que se publicó.

Opino que esta práctica de borrar comentarios no permite hacer un análisis de lo que se publica en ese grupo.

@jonariv09 podrías no borrar los mensajes y dejarlos para que se ser posible en reuniones tocar estos temas?

Recuerden que debemos lograr que se cumplan las normativas, de esta forma si se aprovecha el contenido de calidad, si solo borramos se transmite que se permite publicar cosas fueras del tema principal (JavaScript) pero que alguien lo borra.

**Comment by carloslenondavis** [comment]
Estoy de acuerdo,

Pienso que es un tema de discusión y debería actualizarse las normas de las redes sociales

**Comment by jonariv09** [comment]
Yo no puedo borrar los mensajes, solo los borra quien los puso.

Igual considere eso, porque obviamente si puso algo que ni por cerca, ni al caso en lo absoluto.

Lo hablamos mañana entonces!

**Comment by paulomcnally** [comment]
Ya discutimos esto en reunión semanal.
