### ISSUE TITLE
Reunion Lunes 30 Marzo.

### ISSUE THREAD

**Issue by jonariv09** [js-ni/events#67]
Planeación y temas a abordar en los proximos eventos o los que ya estan en curso

**Comment by jonariv09** [comment]
Team, quisiera que me den su opinion, estos son los temas que considero abordar en la reunion de hoy, si consideran algo que es repetitivo o quizas no tan bien estructurado porfa me dan un feedback.

**Comment by jonariv09** [comment]
Temas a tratar para la reunión:

1. Live del 31 de Marzo / Experiencias
2. Actividades para el mes de Abril, planeación, temática, protocolo.
3. Normas o consideraciones para la administración del grupo de whatsapp.
4. Estructura de la generación de contenido en Slack.
5. Aspectos a considerar con la propuesta de unirnos a la UNI (Guillermo Salazar).
6. Terminos y condiciones para pertenecer a la comunidad.
7. Definición de las herramientas para el manejo de los proyectos OpenSource y los propietarios de cada herramientas.
8. Limitar la creación de canales por usuarios no autorizados.
9. Crear un team para proyectos ideas opensource dirigidos por la comunidad.

**Comment by carloslenondavis** [comment]
La reunion se cancelo.
