### ISSUE TITLE
Expulsión Christopher Oporta del grupo de WhatsApp 

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#69]
El día de hoy se expulsó a alguien que era parte del grupo de WhatsApp.

Dejo las capturas.

![A63F08A9-4FB2-4867-9ED8-D0F2D1000159](https://user-images.githubusercontent.com/181533/78465313-4ceb4f00-76b1-11ea-979c-b09baea33d55.png)

Se toca un tema de C#

![420A4A80-06F6-4FCC-AD3C-2770D19DC521](https://user-images.githubusercontent.com/181533/78465338-ae132280-76b1-11ea-9246-306222c4026d.png)

Se le menciona que no se deben tocar temas fuera de JavaScript.

![35390616-D12C-4420-A973-8D458EA39C17](https://user-images.githubusercontent.com/181533/78465310-4230ba00-76b1-11ea-8f5f-9c84b6bd721d.png)

Menciona haber hablado con Edycar (el que estuvo involucrado con la comunidad Flutter que terminó cerrando) y menciona que Edycar no era patético, por tanto está faltando al respeto.

![67335045-8B31-4710-ABB6-7828B5A9EB13](https://user-images.githubusercontent.com/181533/78465306-3218da80-76b1-11ea-8df3-686be752c524.png)
![C85864CE-B14E-4EA3-BA5C-EB87520CFC79](https://user-images.githubusercontent.com/181533/78465307-3513cb00-76b1-11ea-8640-cf9da6b5bc63.png)
![0F11D83C-DF46-4876-9C09-EF3789BD7CBF](https://user-images.githubusercontent.com/181533/78465308-35ac6180-76b1-11ea-9159-fbfac848877e.png)

Se procede con sacarlo del grupo obviamente avisando antes que ha incumplido las normas.

Sería bueno que habláramos de esto en la reunión del lunes 6 de Abril 2020.

**Comment by carloslenondavis** [comment]
Que tal chicos,

@paulomcnally pero veo que hay varios implicados. Unos por preguntar y otros por responder. Ambos grupos deberían ser advertidos o penalizados.

Por otro, estoy de acuerdo el discutirlo en el meeting y creo que deberiamos buscar un camino en donde disminuir esas partes tensas en el grupo de whatsapp.

**Comment by carloslenondavis** [comment]
@jonariv09 seria bueno anotar esto como un punto de agenda
