### ISSUE TITLE
Validar contenido del arte

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#7]
Una vez hecho el arte, @jonariv09 debes encargarte de validar con Alfonzo Gómez que la información es correcta.

A su vez @clenondavis, @billiramirez y @paulomcnally nos encargaremos de validar los datos generales como día, hora, etc.

**Comment by paulomcnally** [comment]
@LissTrujillo

## Arte seleccionado:
https://user-images.githubusercontent.com/24735404/74900908-d1cf1300-5366-11ea-900a-c3ff6d17cfdc.png

## Solicitud de cambios:

- [ ] Agregar logo de la comunidad JavaScript (Yo te lo pasaré).
- [ ] **JSTalks** remover 2020 y darle una apariencia por lo que es un evento propio (darle realse con arroba o hashtag).
- [ ] Cambiar fecha a 05 de Marzo al 07 de Marzo 2020.
- [ ] Poner ahí: `https://fb.com/JavaScriptNicaragua`
- [ ] Poner algo así en el arte -> https://i.imgur.com/6Xf4Jfn.png

**Comment by billiramirez** [comment]
@paulomcnally es Fb Live o Zoom? En algunos de los artes propuestos estaba las opciones de Fb Live o  Zoom Meeting.

**Comment by dianalih** [comment]
@billiramirez creo que todavía se tiene que discutir eso. 
Les dejo las correcciones pero creo que la información se ve como muy apretada :/  
entonces les adjunto también una de las otras propuestas con algunos cambios para que lo vean :)
![1_1](https://user-images.githubusercontent.com/24735404/75075555-b299c800-54c3-11ea-97d0-79dfeda18965.png)
![1_2](https://user-images.githubusercontent.com/24735404/75075561-b4fc2200-54c3-11ea-9611-a35f0745acb8.png)

**Comment by paulomcnally** [comment]
@LissTrujillo en este https://user-images.githubusercontent.com/24735404/75075555-b299c800-54c3-11ea-97d0-79dfeda18965.png podrias cambiar:

**Alfonzo** por **Alfonso**

Es con `S` y no con `Z`.

Sorry.

**Comment by dianalih** [comment]
![correcciones1](https://user-images.githubusercontent.com/24735404/75389479-2bc26200-58ac-11ea-8a50-e62735a99f8b.png)

**Comment by paulomcnally** [comment]
Gracias @LissTrujillo

**Comment by billiramirez** [comment]
Gracias @LissTrujillo por el apoyo.
