### ISSUE TITLE
Agregar politica en la descripcion del grupo de whatsapp

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/events#70]

**Comment by dave-flr** [comment]
Como miembro nuevo puedo sugerir usar otra cosa en lugar de whatsapp, como discord o telegram. Los bots te facilitan la vida, modo lento, mutear a un usuario en especifico, banear, organizar, bienvenidas, comando para reglas, comando para llamar a los admins etc.

**Comment by paulomcnally** [comment]
Se agregaron las políticas del grupo de WhatsApp -> https://github.com/js-ni/events/blob/master/POLITICS.md#whatsapp-grupo
