### ISSUE TITLE
Herramientas alternativas de Streaming

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#75]
A raíz de un post de la comunidad WordPress Nicaragua me topé con streamyard, lo probé y me gustó mucho, de hecho ya había preguntando por la herramienta (https://twitter.com/PauloMcNally/status/1247216064926285831).

Seria bueno en alguna reunión tocar este tema.

- https://streamyard.com/
- https://zoom.us/
- https://hangouts.google.com/

**Comment by carloslenondavis** [comment]
Pienso, que streamyard, por el momento nos esta resolviendo. Sugiero que podamos irnos por ahi

**Comment by paulomcnally** [comment]
Solo @clenondavis dio sugerencia, opino igual.

Una más de @billiramirez o @jonariv09 y cerramos esto.

**Comment by jonariv09** [comment]
Por mi esta bien StreamYard.

Hangout y Zoom pueden servir en otras actividades quizas luego.

**Comment by billiramirez** [comment]
Por ahora se estará usando StreamYard
