### ISSUE TITLE
Conseguir Sponsors para live

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#8]
- [x] Refrigerio
- [ ] Flayer’s
- [x] Stickers
- [ ] Camisetas
- [ ] Publicidad

Cantidad Personas

1. Alfonso
2. Esposa Alfonso
3. Gustavo
4. Diana
5. Mc
6. Billi

**Comment by hosmelq** [comment]
Hola @paulomcnally en Nerdify pordemos apoyar con el refrigerio y tenemos unos cuantos stickers pero no son de JS xD.

**Comment by carloslenondavis** [comment]
> Hola @paulomcnally en Nerdify pordemos apoyar con el refrigerio y tenemos unos cuantos stickers pero no son de JS xD.

Que tal, @hosmelq como vas?. 

Para efecto de dar seguimiento a tu apoyo con el refrigerio para el `#live del 07 de marzo`. 

Mañana te estaremos compartiendo la info sobre como efectuar dicho apoyo.

Por otro lado, respecto a los stickers, si nos puedes mandar por acá fotos de los stickers así validarlos, será genial.

Desde ya, gracias por el apoyo.
Saludes

**Comment by hosmelq** [comment]
Hola @clenondavis, te dejo una foto de los stickers y quedo pendiente con la info.

Saludos.

![IMG_2193](https://user-images.githubusercontent.com/1166143/75994686-f1b31a80-5ec0-11ea-8fd8-796a8f7bd60d.JPG)

**Comment by paulomcnally** [comment]
No se concretó nada para el Live, esto se puede replicar pero con distinto Milestone @clenondavis @hosmelq
