### ISSUE TITLE
Crear lista de participantes que no han logrado asistir a eventos.

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#80]
Definir un listado de faltas.

Definir cuándo se debe cancelar a usuarios las participaciones por faltas.

Crear un documento con la lista de participantes con faltas y participantes sin faltas.

# Aclaración

Esto aplica para participantes que iban a exponer, no asistentes que van a escuchar/ver charlas.

**Comment by juanpicado** [comment]
Les sugiero que reconsideren esta practica, claramente denota excluir personas, crea una barrera innecesaria a los futuros nuevos miembros, no se puede construir a una comunidad si desde el principio se piensa en excluir, penar o multar.

**Comment by paulomcnally** [comment]
Gracias por el feedback @juanpicado, ya ha sido un tema conversado por los organizadores de la comunidad, quizás más adelante esto cambie, pero por ahora es algo que se ha decidido.

Acá el detalle: https://www.youtube.com/watch?v=TrMy__nd-cc

Saludos

**Comment by paulomcnally** [comment]
No se que opinan de este formato:

https://github.com/js-ni/score/blob/master/README.md

**Comment by billiramirez** [comment]
Voto que sigamos con ese formato que sugirió @paulomcnally
