### ISSUE TITLE
Crear arte para evento - JSTalks - Abril - Convenciones

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#84]
**Título**:

JSTalks - Convenciones

**Temas**:

- Variable
- Función / Método
- Clase
- Nombres de archivos

**Moderadora**:
- Diana Huete

**Panelistas**:
- Alfonso Gómez
- Gabriel Gonzalez
- Luis Guido

**Fecha**:
30.04.20

**Hora**:
06:00 p.m

**Comment by victorstein** [comment]
@paulomcnally lo que solicitaste por whatsapp.
![me](https://user-images.githubusercontent.com/11080740/79518131-7f7c3c80-800d-11ea-87ee-da17eb0d05e5.jpg)

**Comment by hggaguilera** [comment]
@paulomcnally aqui esta mi avatar

![FOTO 2](https://user-images.githubusercontent.com/9381648/79625804-c55a0300-80e8-11ea-998b-3dcbdde2d5ea.png)

**Comment by luchonetvv** [comment]
@LissTrujillo listo aca te dejo mi avatar
![lucho-formal](https://user-images.githubusercontent.com/1069705/79695331-7a003b80-8233-11ea-9bb5-25264a434bb3.jpg)
@paulomcnally listo completado...

**Comment by carloslenondavis** [comment]
> **Título**:
> 
> JSTalks - Convenciones
> 
> **Temas**:
> 
> * Variable
> * Función / Método
> * Clase
> * Nombres de archivos
> 
> **Moderadora**:
> 
> * Diana Huete
> 
> **Panelistas**:
> 
> * Alfonso Gómez
> * Gabriel Gonzalez
> * Luis Guido
> 
> **Fecha**:
> 30.04.20
> 
> **Hora**:
> 06:00 p.m

**Respecto los temas**
Pienso que podemos reemplazar `Nombres de archivos` por `Scaffolding` o `Estructura de archivos`. Esto incluye, nombre de archivos, carpetas, agrupación de archivos y carpetas, etc... No es un tema amplio y así se abarca las convenciones relaciones a este tema, se puede mencionar por ahi, sobre generadores como `yeoman` etc ..

**Comment by dianalih** [comment]
Hola, les dejo dos con dos imagenes diferentes, si creen que no va mucho con el tema me dicen y buscamos otra
![convenciones](https://user-images.githubusercontent.com/24735404/79774270-d58fff00-82ef-11ea-93ce-b24fbcff9a64.png)
![convenciones2](https://user-images.githubusercontent.com/24735404/79774278-d6c12c00-82ef-11ea-8323-2deca86235cc.png)

**Comment by hggaguilera** [comment]
> Hola, les dejo dos con dos imagenes diferentes, si creen que no va mucho con el tema me dicen y buscamos otra
> ![convenciones](https://user-images.githubusercontent.com/24735404/79774270-d58fff00-82ef-11ea-93ce-b24fbcff9a64.png)
> ![convenciones2](https://user-images.githubusercontent.com/24735404/79774278-d6c12c00-82ef-11ea-8323-2deca86235cc.png)

En mi opinion personal, me gusta bastante el primer arte, siento que esta un poco mas de acuerdo con los tres iconos saliendo del codigo

**Comment by paulomcnally** [comment]
Opino igual que @darkalghul

Hoy aprobamos o damos feedback de esto.

Gracias @LissTrujillo

**Comment by paulomcnally** [comment]
Nos quedamos con este

@LissTrujillo  -> https://user-images.githubusercontent.com/24735404/79774270-d58fff00-82ef-11ea-93ce-b24fbcff9a64.png

Gracias!
