### ISSUE TITLE
Crear arte para evento - JSTalks - Mayo -JavaScript 101

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#85]
**Título**:

JSTalks - JavaScript 101

**Temas**:

 - [x] Reseña Historica JS
 - [x] Entornos de Desarrollo en donde corre JS
 - [x] Industrias que lo usan 
 - [x] Demandas laborales

**Expositor**:

Billi Ramirez

**Fecha**:
21.05.20

**Hora**:
06:30 p.m

**Comment by billiramirez** [comment]
**Título**:

JSTalks - JavaScript 101

**Temas**:

Dificultades en Javascript

- Closures

- Promises

 

**Expositor**:

Billi Ramirez

**Fecha**:
23.04.20

**Hora**:
06:00 p.m

**Comment by LissTrujillo** [comment]
Hola, vamos a usar siempre el mismo diseño que se hizo para el primer live?

**Comment by LissTrujillo** [comment]
Billi podrias ayudarme con tus datos:
En el caso de Alfonso pusimos:
5+ años de experiencia
Director de desarrollo de software y aplicaciones en Top Floor Marketing

**Comment by paulomcnally** [comment]
@billiramirez ping.

**Comment by paulomcnally** [comment]
@LissTrujillo Si, a como el JSTalks - GraphQL 101

**Comment by paulomcnally** [comment]
@LissTrujillo disculpa, vamos a definir los temas, esto va para Mayo, así que vamos a pausar tu trabajo de momento.

**Comment by jonariv09** [comment]
Hola @LissTrujillo , ya le dimos paso a la actividad y se le hizo modificación a la fecha, que es para el Jueves 21 de este mes. Te agradeceriamos mucho si pudieras apoyarnos en la creación de este arte. Estaría pendiente los temas, a mas tardar mañana.

**Comment by dianalih** [comment]
Hola chicos! También faltaba la info/descripción de @billiramirez para que lo tengan en cuenta

**Comment by billiramirez** [comment]
Hola @LissTrujillo aquí una breve info:

Trabajo en SolidLogix como Full Stack Software Developer, mi email: billyramirezalex@gmail.com

**Comment by carloslenondavis** [comment]
@LissTrujillo que tal? 
Nos podrías dar feedback de como va el arte para este evento?

**Comment by billiramirez** [comment]
Aquí el issue para los temas:

#87

**Comment by dianalih** [comment]
Hola, les dejo el arte. 
![JS_Billi](https://user-images.githubusercontent.com/24735404/82341520-c31bea80-99ad-11ea-8482-16807d6b0448.png)

**Comment by billiramirez** [comment]
Muchas gracias @LissTrujillo :)

**Comment by jonariv09** [comment]
Gracias @LissTrujillo. 😀

**Comment by jonariv09** [comment]
Creo que podemos cerrar este issue.
