### ISSUE TITLE
Reunion 20 de Abril

### ISSUE THREAD

**Issue by jonariv09** [js-ni/events#86]
Reunion para tratar los siguientes temas:

**Comment by jonariv09** [comment]
- [ ] Observaciones acerca de la aceptación de reglas en las redes sociales 
       a. Whatsapp
       b. Slack
       c. Facebook

- [ ] Creación de canales por usuario sin roles
- [ ] McNally iba a hablar con Alfonso sobre los spots y viñetas
- [x] Avances con la actividad JsTalks Convenciones
- [x] Avances con la actividad JsTalks JavaScript 101
- [ ] Términos y condiciones para pertenecer a la comunidad (issue #64)
       a. Foto de perfil, ¿En cual de todas las redes?
       b. Llenar un issue ¿Con que tipo de información?
       c. ¿Es realmente conveniente esto para miembros generales de la comunidad?
       d. Otros...
- [ ] Reglas para ser un expositor de la comunidad
       a. Nivel de experiencia en el tema a exponer y en JavaScript
       b. Identificar afinidades o intenciones ocultas
       c. Otros...

**Comment by carloslenondavis** [comment]
**Anexo**

- [ ] Retrospectiva meeting pasado
- [ ] Organizacion issues todo (luego de cada meeting)
- [ ] Rol diario/semanal/mensual en el admin de los grupos. Siguiendo la dinamica de owner de los meetings
- [ ] Estructura de los live/meeting, live/events / Esquema o guion. Apoyare
- [ ] Restrospectiva /FODA comunidad y organizadores
- [ ] Politicas Partner || contributors/Sponsors/
- [ ] Dinamica de la semana (Code challenge)
- [ ] Articulo en reconpensa de strike (clenondavis)
- [ ] Apoyo design Events/Marca || Redes sociales
- [ ] Propuesta de @paulomcnally como moderador de grupo desarrolladores Nic

**Comment by carloslenondavis** [comment]
Ya paso la reunion
