### ISSUE TITLE
Definir Temas para JSTalks-Js#101

### ISSUE THREAD

**Issue by billiramirez** [js-ni/events#87]

**Comment by carloslenondavis** [comment]
**Temas**

- Reseña Historica JS
- ECMASCRIPT
- Fisionomía (Tipos de Datos, Variables, Funciones, etc..)
- Entornos de Desarrollo en donde corre JS
- Frameworks y libs mas usados
- Industrias que lo usan
- Demandas laborales
- Lo que es y no es

**Comment by billiramirez** [comment]
- Js & Nodejs es lo mismo? 
- Qué son Aplicaciones Isomórficas en JS?

**Comment by jonariv09** [comment]
1. Conocer la sintaxis de las herramientas básicas de programación como bucles, sentencias if, try / catch, etc.

2. Comprender las definiciones de funciones, incluidas las diversas formas en que se pueden definir y asignar, así como las funciones anónimas

3. Comprender los principios básicos del alcance, alcance global (ventana) versus alcance del objeto (cierres excluidos)

4. Comprender el papel del contexto y el uso de la variable 'this'

5. Comprender las diferentes formas de instanciar y declarar un objeto, así como las funciones como objetos

6. Comprender los operadores de comparación de JavaScript como '<', '>', ' == ', ' === ', lo que es falso y cómo funciona la comparación de objetos y cadenas, así como la conversión

7. Indexacion de matriz para atributos y funciones de objeto y cómo difiere de las matrices reales (literales de objeto frente a literales de matriz)

**Comment by billiramirez** [comment]
Temas elegidos: 

 - [x] Reseña Historica JS
 - [x] Entornos de Desarrollo en donde corre JS
 - [x] Industrias que lo usan 
 - [x] Demandas laborales
