### ISSUE TITLE
Crear arte para evento - JSTalks - Abril - ESLint

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/events#88]
**Título**:

JSTalks - ESLint

**Temas**:

- Instalación.
- Configuración.
- Plugins.

**Expositor**:

Paulo McNally
Full Stack Developer
MOi Solutions

**Fecha**:
23.04.20

**Hora**:
06:00 p.m

**Comment by dianalih** [comment]
Hola adjunto, igual diganme si la imagen no corresponde.
![ESLint](https://user-images.githubusercontent.com/24735404/79910675-53313900-83dc-11ea-9fdb-1e18097f6b5d.png)

**Comment by paulomcnally** [comment]
@LissTrujillo la imagen esta bien.

Gracias! Sos la mejor!

**Comment by jonariv09** [comment]
Esta tuani! (y)

**Comment by carloslenondavis** [comment]
**Buenisimo**, solo que esa tu foto @paulomcnally!!! pareces guerrillero de Osama Binladen jajaajaja
