### ISSUE TITLE
Reunion Lunes 11 Mayo

### ISSUE THREAD

**Issue by jonariv09** [js-ni/events#91]
Propuestas de temas a tratar para la reunion.

**Comment by jonariv09** [comment]
Propongo estos temas para la reunion de hoy:

- [x] Estados de redes sociales:
    - Facebook
    - Whatsapp
    - Slack
- [x] Creación de términos y condiciones para pertenecer a la comunidad
- [x] Desarrollo de la charla Js-Talks 101
- [x] Opiniones en el grupo de whatsapp para la otra charla:
    - Patrones de diseño creando una app de chat
    - Mi primer módulo con JavaScript
- [x] Consideraciones a ampliar la comunidad en su diversidad de temas
- [ ] Inclusión de mujeres desarrolladoras

**Comment by billiramirez** [comment]
Retrospectiva en inactividad en reuniones de organizadores:

- Tener actividades default en caso de inactividad de parte de los organizadores, estas en ocasiones serán lideradas de manera individual. La idea es siempre estar creando contenido.
- Cualquier persona (organizador) quiera realizar una actividad de tipo `default` , al menos comentar al host del mes para así ver de qué manera se pueda apoyar.

**Comment by jonariv09** [comment]
Las tematicas que quedaron sin tratar se plasmaran en este issue: https://github.com/js-ni/events/issues/95
