### ISSUE TITLE
Temas a tratar en la reunion Jueves 21 Mayo

### ISSUE THREAD

**Issue by jonariv09** [js-ni/events#95]
Plasmar los temas que se consideran importantes para tratar en la proxima reunion

**Comment by carloslenondavis** [comment]
- [x] Quorum de votacion e inicio de reunion

**Comment by carloslenondavis** [comment]
- [x] Acceso a las herramientas

**Comment by billiramirez** [comment]
- [x] Aprobaciones de los post a medium

**Comment by jonariv09** [comment]
- [x] Generacion de actividades en las redes sociales (competencias)

**Comment by billiramirez** [comment]
- [x] Mini publicaciones para compartir en las redes sociales.

**Comment by paulomcnally** [comment]
- [x] Distribución de responsabilidades de los organizadores.
- [ ] Propuesta de minimizar la cantidad de reuniones en la semana de 2 a 1.
